#!/bin/sh -e

if [ "$DOCKER_TAG" = "latest" ]; then
	docker tag "$DOCKER_REPO:base-$DOCKER_TAG" "$DOCKER_REPO:base"
	docker push "$DOCKER_REPO:base"
else
	docker push "$DOCKER_REPO:base-$DOCKER_TAG"
fi
